export default {
  AUTH: 'auth',
  BOARDS: 'boards',
  CONS_ID: ':id',
  CONS_PIN_ID: ':pinId',
  CONS_USER_ID: ':userId',
  CONS_USERNAME: ':username',
  CREATE: 'create',
  CREATE_PIN: 'create-pin',
  CREATE_USER: 'create-user',
  FOLLOW: 'follow',
  FORWARDSLASH: '/',
  LOGIN: 'login',
  LOGOUT: 'logout',
  ME: 'me',
  REGISTER: 'register',
  UPDATE: 'update',
  USERNAME: 'username',
}
